#!/bin/bash
echo "
#########################################################################
#                                                                       #
#                                                                       #
#   This script is used to change the permission of files or directory  #
#                                                                       #
#    This should be run with the root privillage for proper execution   #
#                                                                       # 
#                                                                       #
#       This was written by jobijob1@in.ibm.com                         #
#                                                                       #
#                                                                       #
#                                                                       #
#########################################################################"

outputfile=/tmp/chkscript
if [ ! -f $outputfile ]; then
touch /tmp/chkscript
else 
cat /dev/null > $outputfile
fi
echo "Please enter the path to be searched"
read "output"
echo "The path is $output"
if [ ! -d $output ];then
 echo "The path is invalid" 1>&2
rm -rf $outputfile
exit 1
else
pathv=$output
fi
find $pathv -type f >>$outputfile
echo "File search completed please see the outputfile $outputfile"
for i in `cat $outputfile`
do
sed -i '/LDAP/d' $i
done
rm -rf $outputfile
exit

